### ISSUE TITLE
[1.12.2] [Server thread/ERROR] SimplyJetPacks

### ISSUE THREAD

**Issue by MRacingRU** [Tomson124/SimplyJetpacks2#82]
When starting the server, this error appears, but the server is working, I want to know how to make it not happen at all, I'm still worried.
```
[00:16:40] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement simplyjetpacks:ie/root_ie
 com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'immersiveengineering:metal_decoration0'
        at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
        at net.minecraft.advancements.DisplayInfo.func_193221_a(DisplayInfo.java:133) ~[r.class:?]
        at net.minecraft.advancements.DisplayInfo.func_192294_a(DisplayInfo.java:111) ~[r.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(Advancement.java:238) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:517) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188178_a(SourceFile:537) ~[rc.class:?]
        at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$2(ForgeHooks.java:1382) ~[ForgeHooks.class:32e7e1a-DEV]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:32e7e1a-DEV]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1360) [ForgeHooks.class:32e7e1a-DEV]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1327) [ForgeHooks.class:32e7e1a-DEV]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:211) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:426) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
[00:16:40] [Server thread/ERROR] [FML]: Parsing error loading built-in advancement simplyjetpacks:eio/root_eio
 com.google.gson.JsonSyntaxException: Expected item to be an item, was unknown string 'enderio:item_enderface'
        at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:124) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:135) ~[rc.class:?]
        at net.minecraft.advancements.DisplayInfo.func_193221_a(DisplayInfo.java:133) ~[r.class:?]
        at net.minecraft.advancements.DisplayInfo.func_192294_a(DisplayInfo.java:111) ~[r.class:?]
        at net.minecraft.advancements.Advancement$Builder.func_192059_a(Advancement.java:238) ~[i$a.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:50) ~[ns$1.class:?]
        at net.minecraft.advancements.AdvancementManager$1.deserialize(AdvancementManager.java:46) ~[ns$1.class:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[TreeTypeAdapter.class:?]
        at net.minecraft.util.JsonUtils.func_188173_a(SourceFile:492) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188176_a(SourceFile:517) ~[rc.class:?]
        at net.minecraft.util.JsonUtils.func_188178_a(SourceFile:537) ~[rc.class:?]
        at net.minecraftforge.common.ForgeHooks.lambda$loadAdvancements$2(ForgeHooks.java:1382) ~[ForgeHooks.class:32e7e1a-DEV]
        at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:833) [CraftingHelper.class:32e7e1a-DEV]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1360) [ForgeHooks.class:32e7e1a-DEV]
        at net.minecraftforge.common.ForgeHooks.loadAdvancements(ForgeHooks.java:1327) [ForgeHooks.class:32e7e1a-DEV]
        at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:69) [ns.class:?]
        at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) [ns.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:211) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:426) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:688) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_321]
[00:16:40] [Server thread/ERROR] [net.minecraft.advancements.AdvancementList]: Couldn't load advancement simplyjetpacks:eio/jetpack_eio1: Task Advancement{parentId=simplyjetpacks:eio/root_eio, display=net.minecraft.advancements.DisplayInfo@7bc207e0, rewards=AdvancementRewards{experience=1, loot=[], recipes=[], function=null}, criteria={jetpack_eio1=net.minecraft.advancements.Criterion@15583f03}, requirements=[[jetpack_eio1]]}
[00:16:40] [Server thread/ERROR] [net.minecraft.advancements.AdvancementList]: Couldn't load advancement simplyjetpacks:eio/jetpack_eio2: Task Advancement{parentId=simplyjetpacks:eio/jetpack_eio1, display=net.minecraft.advancements.DisplayInfo@753f4c94, rewards=AdvancementRewards{experience=1, loot=[], recipes=[], function=null}, criteria={jetpack_eio2=net.minecraft.advancements.Criterion@21cbc517}, requirements=[[jetpack_eio2]]}
[00:16:40] [Server thread/ERROR] [net.minecraft.advancements.AdvancementList]: Couldn't load advancement simplyjetpacks:eio/jetpack_eio3: Task Advancement{parentId=simplyjetpacks:eio/jetpack_eio2, display=net.minecraft.advancements.DisplayInfo@35cb7542, rewards=AdvancementRewards{experience=1, loot=[], recipes=[], function=null}, criteria={jetpack_eio3=net.minecraft.advancements.Criterion@4a57ed91}, requirements=[[jetpack_eio3]]}
[00:16:40] [Server thread/ERROR] [net.minecraft.advancements.AdvancementList]: Couldn't load advancement simplyjetpacks:eio/jetpack_eio4: Task Advancement{parentId=simplyjetpacks:eio/jetpack_eio3, display=net.minecraft.advancements.DisplayInfo@4b0093a4, rewards=AdvancementRewards{experience=1, loot=[], recipes=[], function=null}, criteria={jetpack_eio4=net.minecraft.advancements.Criterion@3eced430}, requirements=[[jetpack_eio4]]}
[00:16:40] [Server thread/ERROR] [net.minecraft.advancements.AdvancementList]: Couldn't load advancement simplyjetpacks:eio/jetpack_eio5: Task Advancement{parentId=simplyjetpacks:eio/jetpack_eio4, display=net.minecraft.advancements.DisplayInfo@3007d1f1, rewards=AdvancementRewards{experience=1, loot=[], recipes=[], function=null}, criteria={jetpack_eio5=net.minecraft.advancements.Criterion@7820ec95}, requirements=[[jetpack_eio5]]}
[00:16:40] [Server thread/ERROR] [net.minecraft.advancements.AdvancementList]: Couldn't load advancement simplyjetpacks:ie/jetpack_ie3: Task Advancement{parentId=simplyjetpacks:ie/jetpack_ie2, display=net.minecraft.advancements.DisplayInfo@53c76dca, rewards=AdvancementRewards{experience=1, loot=[], recipes=[], function=null}, criteria={jetpack_ie3=net.minecraft.advancements.Criterion@2cfc7763}, requirements=[[jetpack_ie3]]}
[00:16:40] [Server thread/ERROR] [net.minecraft.advancements.AdvancementList]: Couldn't load advancement simplyjetpacks:ie/jetpack_ie2: Task Advancement{parentId=simplyjetpacks:ie/jetpack_ie1, display=net.minecraft.advancements.DisplayInfo@3ae72cde, rewards=AdvancementRewards{experience=1, loot=[], recipes=[], function=null}, criteria={jetpack_eio2=net.minecraft.advancements.Criterion@75ef038e}, requirements=[[jetpack_eio2]]}
[00:16:40] [Server thread/ERROR] [net.minecraft.advancements.AdvancementList]: Couldn't load advancement simplyjetpacks:ie/jetpack_ie1: Task Advancement{parentId=simplyjetpacks:ie/root_ie, display=net.minecraft.advancements.DisplayInfo@5a2dc8cf, rewards=AdvancementRewards{experience=1, loot=[], recipes=[], function=null}, criteria={jetpack_ie1=net.minecraft.advancements.Criterion@57d35377}, requirements=[[jetpack_ie1]]}
```
[https://cdn.discordapp.com/attachments/762945401267159050/956241981326131311/unknown.png](url)

**Comment by jasoncollege24** [comment]
I'm having this same issue, and I think it's causing issues with other advancements, preventing them from triggering, or forcing me to reload my world to get them.
