### ISSUE TITLE
[1.16.5] Clients crash when teleporting to other DIMs near portal in the End

### ISSUE THREAD

**Issue by FoxMcloud5655** [Tomson124/SimplyJetpacks2#83]
I have absolutely no idea why this happens, but when players teleport to another DIM near the End Portal in the End, their client crashes, but the server is fine.  It seems to only happen when the portal is visible.  Going through the actual portal is fine, though.

Version of Simply Jetpacks: 1.16.5-2.6.12.1

```
java.lang.NullPointerException: Unexpected error
	at stormedpanda.simplyjetpacks.handlers.KeybindHandler.tickEnd(KeybindHandler.java:94) ~[?:1.16.5-2.6.12.1] {re:classloading}
	at stormedpanda.simplyjetpacks.handlers.KeybindHandler.onClientTick(KeybindHandler.java:116) ~[?:1.16.5-2.6.12.1] {re:classloading}
```

**Comment by Tomson124** [comment]
Could you please provide the complete crash-log and maybe even client log?

Just to be sure, this happens only when teleporting to a different dimension by command and not the regular way with using portals?

**Comment by FoxMcloud5655** [comment]
It happens whether or not a command is used, but doesn't happen if the user goes through the end portal.  I will try to replicate the issue on my end and send you the client log, since it did not crash on the server and the user has left my server since then.
